### ISSUE TITLE
Tutorial on Hyperbolic Vision Transformers

### ISSUE THREAD

**Issue by diegogcerdas** [maxvanspengler/hyperbolic_learning_library#38]
Hello,

I would like to contribute to a tutorial on [Hyperbolic Vision Transformers](https://arxiv.org/abs/2203.10833) by Ermolov, A. et al (2022). 

The paper describes a vision transformer with output embeddings mapped to the Poincare ball and optimized with a modified pairwise cross-entropy loss.  It is peer-reviewed and accepted at CVPR 2022.

Thank you!

**Comment by maxvanspengler** [comment]
That would be great @diegogcerdas! Thank you for contributing and please let us know if there is anything you could use some help with.

**Comment by maxvanspengler** [comment]
Whoops, accidently hit close instead of comment. My bad!
