### ISSUE TITLE
Curious GPU performance

### ISSUE THREAD

**Issue by DaltonSchutte** [maxvanspengler/hyperbolic_learning_library#59]
Hello! First, great package! It has been a delight to use. One thing I have noticed is that the performance on GPU seems a bit off. To embed a graph of 15k nodes (~100k edges) and modest parameters (dim=2, batch size=512, 10 neg samples per edge) in a Poincare Ball, an epoch takes around 45m and each batch about 12s during training on an H100 (I have confirmed that the model and data is on the proper device). This seems slow considering the power of the hardware and that I can train LLMs on this device more quickly (not a perfect apples-to-apples comparison of course, but is what partly makes me wonder about the performance). The training proceeds normally and I do get good embeddings with smaller batch sizes and graphs, however it seems odd that the process with the above parameters would take an estimated 26 days to train.

I'm curious what your experience has been when training embeddings on GPUs and if you might have any tips for speeding things up? Looking through the code, there were nothing that stood out to me as being likely to cause this issue...

**Comment by maxvanspengler** [comment]
Hi there and thanks for your interest in our library! 

Are you mostly using the code from our Poincaré embeddings tutorial? If so, I vaguely remember that the way in which we sample negative edges becomes prohibitively slow for larger lists, so that might be the problem. Would you be able to do some profiling to identify the bottleneck?

Besides that, does the problem only appear when training on GPUs or does it happen on CPU as well?

**Comment by DaltonSchutte** [comment]
Ahhh yes. It seems to be the data loading process. I will work on some modifications to the data loading. Would you want an efficient implementation of a graph sampler for this package? It seems like it might be out of scope. Otherwise, I could contribute a modified version of the example if you like. :)

**Comment by maxvanspengler** [comment]
I agree that we probably shouldn't make the sampling too complicated in this tutorial, so I think what @philippmwirth proposes makes sense. Then we can also add a small note next to the current sampler regarding the problems that appear when trying to scale it up to larger datasets and point to your efficient implementation. Would you still be willing to contribute something like that @DaltonSchutte? It would be greatly appreciated :)
